SELECT CASE
  WHEN EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'DBRO_USER')
  THEN format('ALTER ROLE %I LOGIN PASSWORD %L', :'DBRO_USER', :'DBRO_PASSWORD')
  ELSE format('CREATE ROLE %I LOGIN PASSWORD %L', :'DBRO_USER', :'DBRO_PASSWORD')
END AS sql
\gexec

SELECT CASE
  WHEN EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'DBRW_USER')
  THEN format('ALTER ROLE %I LOGIN PASSWORD %L', :'DBRW_USER', :'DBRW_PASSWORD')
  ELSE format('CREATE ROLE %I LOGIN PASSWORD %L', :'DBRW_USER', :'DBRW_PASSWORD')
END AS sql
\gexec

SELECT format('GRANT CONNECT ON DATABASE %I TO %I', :'APP_DB_NAME', :'DBRO_USER') AS sql
\gexec

SELECT format('GRANT CONNECT ON DATABASE %I TO %I', :'APP_DB_NAME', :'DBRW_USER') AS sql
\gexec

SELECT format('GRANT USAGE ON SCHEMA public TO %I, %I', :'DBRO_USER', :'DBRW_USER') AS sql
\gexec

SELECT format('GRANT SELECT ON ALL TABLES IN SCHEMA public TO %I', :'DBRO_USER') AS sql
\gexec

SELECT format('GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO %I', :'DBRO_USER') AS sql
\gexec

SELECT format(
  'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO %I',
  :'DBRW_USER')
AS sql
\gexec

SELECT format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO %I', :'DBRW_USER') AS sql
\gexec

SELECT format(
  'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public GRANT SELECT ON TABLES TO %I',
  :'APP_DB_OWNER', :'DBRO_USER')
AS sql
\gexec

SELECT format(
  'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public GRANT SELECT ON SEQUENCES TO %I',
  :'APP_DB_OWNER', :'DBRO_USER')
AS sql
\gexec

SELECT format(
  'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I',
  :'APP_DB_OWNER', :'DBRW_USER')
AS sql
\gexec

SELECT format(
  'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO %I',
  :'APP_DB_OWNER', :'DBRW_USER')
AS sql
\gexec
